#!/bin/bash
cd "$(dirname "$(realpath "$0")")"/ # <-- CD into the directory that this script is in

# Setup
source ../../env

# Execute Actual commands we care about
(
    set -e
    mkdir .tmp
    $py3 "download tmp files.py"
    $py3 "push base csv.py"
    $py3 "add serving since.py"
    $py3 "get twitter ids from handles.py"
)
