#!/bin/bash
cd "$(dirname "$(realpath "$0")")"/ # <-- CD into the directory that this script is in

# Setup
source ../env

# Execute Actual commands we care about
(
    set -e
    $py3 ingest.py
) 2>&1 | tee lastrun # <-- this last part sends a copy of the output to a file called lastrun
