#!/bin/bash
cd "$(dirname "$(realpath "$0")")"/ # <-- CD into the directory that this script is in

# Setup
source ../../env

# Execute Actual commands we care about
(
    set -e
    ./federal-legislators/update
    ./state-legislators/pull
    $py3 "get twitter ids from handles.py"
)
